services:
  db:
    container_name: leafjots-db
    image: postgres:16
    environment:
      POSTGRES_DB: leafjots
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["54377:5432"]
    volumes: [leafjots-db-data:/var/lib/postgresql/data]
    networks:
      - leafjots-network
  redis:
    container_name: leafjots-redis
    image: redis:7-alpine
    ports: ["6380:6379"]
    networks:
      - leafjots-network
volumes:
  leafjots-db-data:
networks:
  leafjots-network:
    name: leafjots-network
